export const CHANGE_VALUE_IN_TAB = "CHANGE_VALUE_IN_TAB";
export const RESOLVE_EXPRESSION = "RESOLVE_EXPRESSION";
export const CLEAN_FIELD = "CLEAN_FIELD";
export const DELETE_ONE_A_TIME = "DELETE_ONE_A_TIME";